"""Shared NFC_PERSIST_ID_* values — keep in sync with src/nfc/router/service.h."""

NFC_PERSIST_ID_NDEF = 0x01
NFC_PERSIST_ID_DESFIRE = 0x02
NFC_PERSIST_ID_ULTRALIGHT = 0x03
NFC_PERSIST_ID_EMV = 0x04
NFC_PERSIST_ID_ALIRO = 0x05
NFC_PERSIST_ID_CLASSIC = 0x06
NFC_PERSIST_ID_FELICA = 0x07
NFC_PERSIST_ID_ISO15693 = 0x08
NFC_PERSIST_ID_SLIX = 0x09
NFC_PERSIST_ID_ST25TB = 0x0A

NFC_STORE_ENTRY_FLAG_READER_CAPTURED = 1 << 0
NFC_STORE_ENTRY_FLAG_HAND_AUTHORED = 1 << 1
NFC_STORE_ENTRY_FLAG_EMULATION_COMPLETE = 1 << 2

# Hand-authored baseline flags per persist_id (wave6-store §Task 16).
PERSIST_HAND_FLAGS: dict[int, int] = {
    NFC_PERSIST_ID_NDEF: NFC_STORE_ENTRY_FLAG_EMULATION_COMPLETE,
    NFC_PERSIST_ID_ULTRALIGHT: NFC_STORE_ENTRY_FLAG_EMULATION_COMPLETE,
    NFC_PERSIST_ID_EMV: NFC_STORE_ENTRY_FLAG_EMULATION_COMPLETE,
    NFC_PERSIST_ID_DESFIRE: NFC_STORE_ENTRY_FLAG_EMULATION_COMPLETE,
    NFC_PERSIST_ID_ALIRO: NFC_STORE_ENTRY_FLAG_EMULATION_COMPLETE,
}
